'use strict';

const MORSE = {
    _0: {sym: "0", code: "-----", word:"zero"},
    _1: {sym: "1", code: ".----", word:"one"},
    _2: {sym: "2", code: "..---", word:"two"},
    _3: {sym: "3", code: "...--", word:"three"},
    _4: {sym: "4", code: "....-", word:"four"},
    _5: {sym: "5", code: ".....", word:"five"},
    _6: {sym: "6", code: "-....", word:"six"},
    _7: {sym: "7", code: "--...", word:"seven"},
    _8: {sym: "8", code: "---..", word:"eight"},
    _9: {sym: "9", code: "----.", word:"nine"},
    a: {sym: "A", code: ".-", word:"alpha"},
    b: {sym: "B", code: "-...", word:"bravo"},
    c: {sym: "C", code: "-.-.", word:"charlie"},
    d: {sym: "D", code: "-..", word:"delta"},
    e: {sym: "E", code: ".", word:"echo"},
    f: {sym: "F", code: "..-.", word:"foxtrot"},
    g: {sym: "G", code: "--.", word:"golf"},
    h: {sym: "H", code: "....", word:"hotel"},
    i: {sym: "I", code: "..", word:"india"},
    j: {sym: "J", code: ".---", word:"juliet"},
    k: {sym: "K", code: "-.-", word:"kilo"},
    l: {sym: "L", code: ".-..", word:"lima"},
    m: {sym: "M", code: "--", word:"mike"},
    n: {sym: "N", code: "-.", word:"november"},
    o: {sym: "O", code: "---", word:"oscar"},
    p: {sym: "P", code: ".--.", word:"papa"},
    q: {sym: "Q", code: "--.-", word:"quebec"},
    r: {sym: "R", code: ".-.", word:"romeo"},
    s: {sym: "S", code: "...", word:"sierra"},
    t: {sym: "T", code: "-", word:"tango"},
    u: {sym: "U", code: "..-", word:"uniform"},
    v: {sym: "V", code: "...-", word:"victor"},
    w: {sym: "W", code: ".--", word:"whiskey"},
    x: {sym: "X", code: "-..-", word:"x-ray"},
    y: {sym: "Y", code: "-.--", word:"yankee"},
    z: {sym: "Z", code: "--..", word:"zulu"},
    error: {sym: "error", code: "........", word:"error"},
    dollar: {sym: "$", code: "...-..-", word:"Dollar"},
    quotation: {sym: "\"", code: ".-..-.", word:"Quotation"},
    start: {sym: "start", code: "-.-.-", word:"start"},
    period: {sym: ".", code: ".-.-.-", word:"period"},
    comma: {sym: ",", code: "--..--", word:"comma"},
    question: {sym: "?", code: "..--..", word:"Question"},
    apostrophe: {sym: "'", code: ".---.", word:"Apostrophe"},
    exclamation: {sym: "!", code: "-.-.--", word:"Exclamation"},
    slash: {sym: "/", code: "-..-.", word:"Slash"},
    parenthesis_open: {sym: "(", code: "-.--.", word:"Parenthesis Open"},
    parenthesis_close: {sym: ")", code: "-.--.-", word:"Parenthesis Close"},
    ampersand: {sym: "&", code: ".-...", word:"Ampersand"},
    colon: {sym: ":", code: "-.-.-.", word:"Colon"},
    semicolon: {sym: ";", code: "-.-.-.", word:"Semicolon"},
    equals: {sym: "=", code: "-...-", word:"Equals"},
    plus: {sym: "+", code: ".-.-.", word:"Plus"},
    minus: {sym: "-", code: "-....-", word:"Minus"},
    underscore: {sym: "_", code: "..--.-", word:"Underscore"},
    at: {sym: "@", code: ".--.-.", word:"@"},
    end: {sym: "end", code: "...-.-", word:"End"},
}

const MORSE_ARR = Object.entries(MORSE).map(([k,v])=>v)
