'use strict';

const MORSE = [
    {sym: "0", code: "-----", word:"zero"},
    {sym: "1", code: ".----", word:"one"},
    {sym: "2", code: "..---", word:"two"},
    {sym: "3", code: "...--", word:"three"},
    {sym: "4", code: "....-", word:"four"},
    {sym: "5", code: ".....", word:"five"},
    {sym: "6", code: "-....", word:"six"},
    {sym: "7", code: "--...", word:"seven"},
    {sym: "8", code: "---..", word:"eight"},
    {sym: "9", code: "----.", word:"nine"},
    {sym: "A", code: ".-", word:"alpha"},
    {sym: "B", code: "-...", word:"bravo"},
    {sym: "C", code: "-.-.", word:"charlie"},
    {sym: "D", code: "-..", word:"delta"},
    {sym: "E", code: ".", word:"echo"},
    {sym: "F", code: "..-.", word:"foxtrot"},
    {sym: "G", code: "--.", word:"golf"},
    {sym: "H", code: "....", word:"hotel"},
    {sym: "I", code: "..", word:"india"},
    {sym: "J", code: ".---", word:"juliet"},
    {sym: "K", code: "-.-", word:"kilo"},
    {sym: "L", code: ".-..", word:"lima"},
    {sym: "M", code: "--", word:"mike"},
    {sym: "N", code: "-.", word:"november"},
    {sym: "O", code: "---", word:"oscar"},
    {sym: "P", code: ".--.", word:"papa"},
    {sym: "Q", code: "--.-", word:"quebec"},
    {sym: "R", code: ".-.", word:"romeo"},
    {sym: "S", code: "...", word:"sierra"},
    {sym: "T", code: "-", word:"tango"},
    {sym: "U", code: "..-", word:"uniform"},
    {sym: "V", code: "...-", word:"victor"},
    {sym: "W", code: ".--", word:"whiskey"},
    {sym: "X", code: "-..-", word:"x-ray"},
    {sym: "Y", code: "-.--", word:"yankee"},
    {sym: "Z", code: "--..", word:"zulu"},
    {sym: "error", code: "........", word:"error"},
    {sym: "$", code: "...-..-", word:"Dollar"},
    {sym: "\"", code: ".-..-.", word:"Quotation"},
    {sym: "start", code: "-.-.-", word:"start"},
    {sym: ".", code: ".-.-.-", word:"period"},
    {sym: ",", code: "--..--", word:"comma"},
    {sym: "?", code: "..--..", word:"Question"},
    {sym: "'", code: ".---.", word:"Apostrophe"},
    {sym: "!", code: "-.-.--", word:"Exclamation"},
    {sym: "/", code: "-..-.", word:"Slash"},
    {sym: "(", code: "-.--.", word:"Parenthesis Open"},
    {sym: ")", code: "-.--.-", word:"Parenthesis Close"},
    {sym: "&", code: ".-...", word:"Ampersand"},
    {sym: ":", code: "-.-.-.", word:"Colon"},
    {sym: ";", code: "-.-.-.", word:"Semicolon"},
    {sym: "=", code: "-...-", word:"Equals"},
    {sym: "+", code: ".-.-.", word:"Plus"},
    {sym: "-", code: "-....-", word:"Minus"},
    {sym: "_", code: "..--.-", word:"Underscore"},
    {sym: "@", code: ".--.-.", word:"@"},
    {sym: "end", code: "...-.-", word:"End"},
]
