;
CREATE USER IF NOT EXISTS "OUTLINE-PROD" SALT '583ceba9c3f4882f' HASH 'a697964bcd3719a94ee3ea06ed4bdb8bd2ada3182144c7a6a5ad0ea58ca4c9e8' ADMIN;
CREATE SEQUENCE PUBLIC.HIBERNATE_SEQUENCE START WITH 3;
CREATE CACHED TABLE PUBLIC.PARAGRAPH(
    ID BIGINT NOT NULL,
    NAME VARCHAR(255) NOT NULL,
    OWNER_ID BIGINT,
    PARENTPARAGRAPH_ID BIGINT,
    CHILDPARAGRAPHS_ORDER INTEGER
);
ALTER TABLE PUBLIC.PARAGRAPH ADD CONSTRAINT PUBLIC.CONSTRAINT_1 PRIMARY KEY(ID);
-- 0 +/- SELECT COUNT(*) FROM PUBLIC.PARAGRAPH;
CREATE CACHED TABLE PUBLIC.PARAGRAPH_TAG(
    PARAGRAPH_ID BIGINT NOT NULL,
    TAGS_ID BIGINT NOT NULL
);
ALTER TABLE PUBLIC.PARAGRAPH_TAG ADD CONSTRAINT PUBLIC.CONSTRAINT_9 PRIMARY KEY(PARAGRAPH_ID, TAGS_ID);
-- 0 +/- SELECT COUNT(*) FROM PUBLIC.PARAGRAPH_TAG;
CREATE CACHED TABLE PUBLIC.ROLE(
    ID BIGINT NOT NULL,
    NAME VARCHAR(255) NOT NULL
);
ALTER TABLE PUBLIC.ROLE ADD CONSTRAINT PUBLIC.CONSTRAINT_2 PRIMARY KEY(ID);
-- 1 +/- SELECT COUNT(*) FROM PUBLIC.ROLE;
INSERT INTO PUBLIC.ROLE(ID, NAME) VALUES
(1, 'ADMIN');
CREATE CACHED TABLE PUBLIC.TAG(
    ID BIGINT NOT NULL,
    NAME VARCHAR(255) NOT NULL
);
ALTER TABLE PUBLIC.TAG ADD CONSTRAINT PUBLIC.CONSTRAINT_14 PRIMARY KEY(ID);
-- 0 +/- SELECT COUNT(*) FROM PUBLIC.TAG;
CREATE CACHED TABLE PUBLIC.TOPIC(
    ID BIGINT NOT NULL,
    IMAGES VARCHAR(255),
    NAME VARCHAR(255) NOT NULL,
    OWNER_ID BIGINT,
    PARAGRAPH_ID BIGINT NOT NULL,
    TOPICS_ORDER INTEGER
);
ALTER TABLE PUBLIC.TOPIC ADD CONSTRAINT PUBLIC.CONSTRAINT_4 PRIMARY KEY(ID);
-- 0 +/- SELECT COUNT(*) FROM PUBLIC.TOPIC;
CREATE CACHED TABLE PUBLIC.TOPIC_TAG(
    TOPIC_ID BIGINT NOT NULL,
    TAGS_ID BIGINT NOT NULL
);
ALTER TABLE PUBLIC.TOPIC_TAG ADD CONSTRAINT PUBLIC.CONSTRAINT_B PRIMARY KEY(TOPIC_ID, TAGS_ID);
-- 0 +/- SELECT COUNT(*) FROM PUBLIC.TOPIC_TAG;
CREATE CACHED TABLE PUBLIC.USER(
    ID BIGINT NOT NULL,
    NAME VARCHAR(255) NOT NULL,
    PASSWORD VARCHAR(255) NOT NULL
);
ALTER TABLE PUBLIC.USER ADD CONSTRAINT PUBLIC.CONSTRAINT_27 PRIMARY KEY(ID);
-- 1 +/- SELECT COUNT(*) FROM PUBLIC.USER;
INSERT INTO PUBLIC.USER(ID, NAME, PASSWORD) VALUES
(2, 'admin', '$2a$10$pxowDnMLBAmqVLNgNsjxv.Uo3.dfrsi.HRjJ6sPUBJP4vGy7JDjEq');
CREATE CACHED TABLE PUBLIC.USER_ROLE(
    USER_ID BIGINT NOT NULL,
    ROLES_ID BIGINT NOT NULL
);
ALTER TABLE PUBLIC.USER_ROLE ADD CONSTRAINT PUBLIC.CONSTRAINT_BC PRIMARY KEY(USER_ID, ROLES_ID);
-- 1 +/- SELECT COUNT(*) FROM PUBLIC.USER_ROLE;
INSERT INTO PUBLIC.USER_ROLE(USER_ID, ROLES_ID) VALUES
(2, 1);
ALTER TABLE PUBLIC.USER ADD CONSTRAINT PUBLIC.UK_SYFTR7GX86FWF7OX7BGVNNTA7 UNIQUE(NAME);
ALTER TABLE PUBLIC.PARAGRAPH_TAG ADD CONSTRAINT PUBLIC.FKQ0LSLEHWXA3NKKV3TJNOHIF8W FOREIGN KEY(PARAGRAPH_ID) REFERENCES PUBLIC.PARAGRAPH(ID) NOCHECK;
ALTER TABLE PUBLIC.PARAGRAPH ADD CONSTRAINT PUBLIC.FKAQ7NMC9MKS1WL3O6IO77V8THJ FOREIGN KEY(OWNER_ID) REFERENCES PUBLIC.USER(ID) NOCHECK;
ALTER TABLE PUBLIC.USER_ROLE ADD CONSTRAINT PUBLIC.FK7QNWWE579G9FROLYPRAT52L4D FOREIGN KEY(ROLES_ID) REFERENCES PUBLIC.ROLE(ID) NOCHECK;
ALTER TABLE PUBLIC.TOPIC ADD CONSTRAINT PUBLIC.FK2U2FLCP4SNW5LLW8Y5VKDMCPW FOREIGN KEY(OWNER_ID) REFERENCES PUBLIC.USER(ID) NOCHECK;
ALTER TABLE PUBLIC.PARAGRAPH_TAG ADD CONSTRAINT PUBLIC.FKNR1KQJM2HO0CNV344NAXCTH8V FOREIGN KEY(TAGS_ID) REFERENCES PUBLIC.TAG(ID) NOCHECK;
ALTER TABLE PUBLIC.PARAGRAPH ADD CONSTRAINT PUBLIC.FKTK57SNTG1BE4TXENN83LQ6231 FOREIGN KEY(PARENTPARAGRAPH_ID) REFERENCES PUBLIC.PARAGRAPH(ID) NOCHECK;
ALTER TABLE PUBLIC.TOPIC ADD CONSTRAINT PUBLIC.FKDHMKOTMYYELUN0GHFN2JJMMJR FOREIGN KEY(PARAGRAPH_ID) REFERENCES PUBLIC.PARAGRAPH(ID) NOCHECK;
ALTER TABLE PUBLIC.TOPIC_TAG ADD CONSTRAINT PUBLIC.FKETILC466TPWYNTUUXQBJ00M06 FOREIGN KEY(TAGS_ID) REFERENCES PUBLIC.TAG(ID) NOCHECK;
ALTER TABLE PUBLIC.TOPIC_TAG ADD CONSTRAINT PUBLIC.FK688SUGEPY0EFQMQQQV9FNGA78 FOREIGN KEY(TOPIC_ID) REFERENCES PUBLIC.TOPIC(ID) NOCHECK;
ALTER TABLE PUBLIC.USER_ROLE ADD CONSTRAINT PUBLIC.FKC52D1RV3IJBPU6LO2V3REJ1TX FOREIGN KEY(USER_ID) REFERENCES PUBLIC.USER(ID) NOCHECK;
