'use strict';

const MORSE = {
    _0: {sym: "0", code: "-----"},
    _1: {sym: "1", code: ".----"},
    _2: {sym: "2", code: "..---"},
    _3: {sym: "3", code: "...--"},
    _4: {sym: "4", code: "....-"},
    _5: {sym: "5", code: "....."},
    _6: {sym: "6", code: "-...."},
    _7: {sym: "7", code: "--..."},
    _8: {sym: "8", code: "---.."},
    _9: {sym: "9", code: "----."},
    a: {sym: "A", code: ".-"},
    b: {sym: "B", code: "-..."},
    c: {sym: "C", code: "-.-."},
    d: {sym: "D", code: "-.."},
    e: {sym: "E", code: "."},
    f: {sym: "F", code: "..-."},
    g: {sym: "G", code: "--."},
    h: {sym: "H", code: "...."},
    i: {sym: "I", code: ".."},
    j: {sym: "J", code: ".---"},
    k: {sym: "K", code: "-.-"},
    l: {sym: "L", code: ".-.."},
    m: {sym: "M", code: "--"},
    n: {sym: "N", code: "-."},
    o: {sym: "O", code: "---"},
    p: {sym: "P", code: ".--."},
    q: {sym: "Q", code: "--.-"},
    r: {sym: "R", code: ".-."},
    s: {sym: "S", code: "..."},
    t: {sym: "T", code: "-"},
    u: {sym: "U", code: "..-"},
    v: {sym: "V", code: "...-"},
    w: {sym: "W", code: ".--"},
    x: {sym: "X", code: "-..-", word},
    y: {sym: "Y", code: "-.--"},
    z: {sym: "Z", code: "--.."},
    error: {sym: "error", code: "........"},
    dollar: {sym: "$", code: "...-..-"},
    quotation: {sym: "\"", code: ".-..-."},
    start: {sym: "start", code: "-.-.-"},
    period: {sym: ".", code: ".-.-.-"},
    comma: {sym: ",", code: "--..--"},
    question: {sym: "?", code: "..--.."},
    apostrophe: {sym: "'", code: ".---."},
    exclamation: {sym: "!", code: "-.-.--"},
    slash: {sym: "/", code: "-..-."},
    parenthesis_open: {sym: "(", code: "-.--.", },
    parenthesis_close: {sym: ")", code: "-.--.-", },
    ampersand: {sym: "&", code: ".-..."},
    colon: {sym: ":", code: "---..."},
    semicolon: {sym: ";", code: "-.-.-."},
    equals: {sym: "=", code: "-...-"},
    plus: {sym: "+", code: ".-.-."},
    minus: {sym: "-", code: "-....-"},
    underscore: {sym: "_", code: "..--.-"},
    at: {sym: "@", code: ".--.-."},
    end: {sym: "end", code: "...-.-"},
}

const MORSE_ARR = Object.entries(MORSE).map(([k,v])=>v)
